drops:
  drop_regions:
    shipping_box_0_impeding:
      frame: shipping_box_0::box_base
      min:
        xyz: [-0.15, -0.35, 0.0]
      max:
        xyz: [0.15, 0.35, 0.5]
      destination:
        xyz: [0.15, 0.15, 0.05]
        rpy: [0, 0, 0.2]
      product_type_to_drop: gear_part
