drops:
  drop_regions:
    bin3_reachable:
      min:
        xyz: [-0.85, 0.7, 0.7]
      max:
        xyz: [-0.65, 1.60, 1.3]
      destination:
        xyz: [-0.65, 1.15, 0.76]
        rpy: [0, 0, 0.5]
      product_type_to_drop: gear_part
